### ISSUE TITLE
RPCError: signature is not valid at get-notifications.js

### ISSUE THREAD

**Issue by binoalien** [scorum/scorum-side-js#1]
Hello,
i want to use get-notifications.js at the mainnet (https://blog-api.scorum.com/) but i get "RPCError: signature is not valid."

Is this a problem with der socrumd from https://blog-api.scorum.com/ ?

And a other question:
Is there a plan for a setVote function?

best regards,
binoalien

**Comment by evercoinx** [comment]
Hi @binoalien 

> i want to use get-notifications.js at the mainnet (https://blog-api.scorum.com/) but i get "RPCError: signature is not valid."

Actually _getNotifications_ method has been updated during the latest release 1.10.0. So please give a try again now.

> Is there a plan for a setVote function?

No, it's not planned to add it at least for the upcoming release.

**Comment by binoalien** [comment]
Hi @grizerg 
thank you for your answer.
i have the same error on (https://blog-api.scorum.com/) but on devchain (https://blog-api-dev.scorum.com/) i haven't a problem.

Has https://blog-api-dev.scorum.com/ an newer socrumd then https://blog-api.scorum.com/ ?
The error looks like the RPC method for getNotifications is not on https://blog-api.scorum.com/

**Comment by evercoinx** [comment]
@binoalien Basically the difference is quite straightforward -- blog-api.scorum.com relates to the production stage while blog-api-dev.scorum.com to the development one. So you're right that _blog-api-dev_ can be a bit fresher in terms of new functionality.
